from . import start
from . import cv
from . import contact
from . import skills
from . import experiencia
from . import formacion
from . import start
from . import cv
from . import contact
from . import skills
from . import experiencia
from . import formacion
from . import callbacks
